export class Product {
    id: number = -1;
    brand: string = '';
    name: string = '';
    categoryId: number = 0;
    description: string = '';
    pure: boolean = false;
    img: string = '';
}

{
    products: [
        {
            id:1,
            brand: 'La roche posay',
            name: 'Lipikar testápló tej',
            categoryId: 1,
            description: 'A LIPIKAR TESTÁPOLÓ TEJ illatanyagmentes formulája akár 48 órán át hidratálja a bőrt, csökkenti a feszülő érzést és rugalmasságot nyújt az érzékeny bőr számára. Csecsemőktől az idősekig minden korosztálynak.',
            pure: true,
            img: '',
        },
        {
            id:2,
            brand: 'La roche posay',
            name: 'Lipikar tusfürdő gél',
            categoryId: 1,
            description: 'A Lipikar Tusfürdő gél kíméletesen tisztítja meg a bőrt. Arcra és testre is megfelelő. Nyugtatja és óvja az érzékeny, száraz bőrt. Bőrnyugtató niacinamide és lipidpótló shea vaj hatóanyagokkal gazdagított formula a hidratált bőrért közvetlenül zuhanyozás után.',
            pure: true,
            img: '',
        },
        {
            id:3,
            brand: 'La roche posay',
            name: 'Lipikar surgras',
            categoryId: 1,
            description: 'A száraz és érzékeny bőrre kifejlesztett LIPIKAR Surgras Hidratáló krém-tusfürdő gyengéden tisztítja a bőrt és pótolja a szükséges lipideket, ezáltal segít megőrizni a bőr természetes védőrétegét.',
            pure: true,
            img:'',
        },
        {
            id:4,
            brand:'La roche posay',
            name:'Lipikar xerand',
            categoryId: 1,
            description: 'A nagyon száraz és irritált kezek bőrét védő barrier meggyengült az ismételt stresszhatások miatt (pl. hideg, időjárási feltételek, gyakori kézmosás, stb.). Hidratáló és tápláló összetevőinek köszönhetően a LIPIKAR Xerand Kézkrém támogatja a bőrbarriert és óvja a bőrt a mindennapi stresszfaktoroktól.',
            pure: true,
            img:'',
        },
        {
            id:5,
            brand: 'La roche posay',
            name: 'Lipikar balzsam AP+M',
            categoryId: 2,
            description: 'A LIPIKAR AP+M Testápoló balzsam segít fenntartani a mikrobiom egyensúlyát. Azonnal nyugtatja a bőrt és enyhíti a viszketést. Kiújulásgátló hatékonysága által segít meghosszabbítani a nyugalmi állapotot. Táplálja a bőrt, támogatja a bőr barrierfunkcióját. Nagyon száraz, ekcémára vagy allergiára hajlamos bőrre, babák, gyermekek és felnőttek számára kifejlesztve.',
            pure: true,
            img:'',
        },
        {
            id:6,
            brand: 'La roche posay',
            name: 'Lipikar syndet AP+',
            categoryId: 2,
            description: 'A Lipikar AP+ SYNDET Kímélő krém-tusfürdő megfelelő nagyon száraz, atópiás ekcémára hajlamos bőrre újszülöttek, csecsemők, gyermekek és felnőttek számára. Megfelelő érzékeny, nagyon száraz, viszketésre hajlamos bőrre. Alkalmazható kisbabák fejbőrére és koszmós bőr ápolására. Ez a krémtusfürdő syndet azonnal nyugtatja a bőrt és segít csökkenteni a bőrszárazságot már a zuhanyzást követően.',
            pure: true,
            img:'',
        },
        {
            id:7,
            brand:'La roche posay',
            name: 'Lipikar tusfürdő olaj AP+',
            categoryId: 2,
            description: 'A LIPIKAR AP+ Tusfürdő olaj dörzsölés nélkül tisztítja a nagyon száraz, érzékeny bőrt. Hidratál, segít visszanyerni a komfortérzetet és csökkenteni az irritációt, óvja a bőrt a kemény víz szárító hatásától. Az egész család számára ajánlott, a babától az idősekig.',
            pure: true,
            img:'',
        },
        {
            id:8,
            brand:'La roche posay',
            name:'Lipikar stift AP+',
            categoryId: 2,
            description: 'LIPIKAR AP+ STIFT azonnal csillapítja a vakarózási ingert és nyugtatja a bőrt. Bárhol, bármikor.',
            pure: true,
            img: '',
        },
        {
            id:9,
            brand: 'La roche posay',
            name: 'Effaclar duo+',
            categoryId: 3,
            description: 'Az EFFACLAR DUO(+) egy teljes körű bőrápoló megerősített hatékonysággal a bőrhibák ellen. Segít gyorsan kitisztítani a meglévő bőrhibákat, hozzájárul a kiújulás és a foltok megelőzéséhez.',
            pure: false,
            img:'',
        },
        {
            id:10,
            brand:'La roche posay',
            name:'Effaclar mikro hámlasztó gél',
            categoryId: 3,
            description: 'EFFACLAR Mikro-hámlasztó tisztító gél intenzíven tisztítja a zsíros bőrt, az eltömődött pórusokat és eltávolítja a felesleges faggyút. Rendszeres használatával segít fokozatosan és tartósan csökkenteni a makacs bőrhibákat, beleértve a pattanások után megmaradó foltokat is',
            pure: false,
            img: '',
        },
        {
            id:11,
            brand:'La roche posay',
            name:'Effaclar micellás arctisztító',
            categoryId: 3,
            description: 'EFFACLAR MICELLÁS ARCTISZTÍTÓ a zsíros, érzékeny, bőrhibákra hajlamos arcbőrre. La Roche-Posay Termálvízzel gazdagított micellás víz, mely gyengéden távolítja el a szennyeződéseket, a faggyút és a sminket, és tiszta és üde érzést ad a bőrnek.',
            pure: false,
            img: '',
        },
        {
            id:12,
            brand:'La roche posay',
            name: 'Effaclar K',
            categoryId: 3,
            description:'Az EFFACLAR K (+) a La Roche-Posay első bőrmegújító arcápolója zsíros bőrre a kiújuló mitesszerek oxidációjának megelőzéséért, antioxidáns és akár 8 órán tartó faggyú elleni hatással. A bőr már az első alkalmazást követően sima tapintású lehet. Ideális kiújuló mitesszerek és egyenetlen bőrtextúra esetén.', 
            pure: false,
            img:'',
        },
        {
            id:13,
            brand:'La roche posay',
            name: 'Effaclar M',
            categoryId: 3,
            description: 'Az EFFACLAR MAT egy faggyútermelés-szabályozó hidratáló krém amely az aknéra hajlamos, zsíros bőr kifényesedését célozza és összehúzza a pórusokat.',
            pure: false,
            img:'',
        },
        {
            id:14,
            brand:'La roche posay',
            name: 'Effaclar tonic',
            categoryId: 3,
            description: 'Az EFFACLAR Mikro-hámlasztó pórusösszehúzó tonik segít kitisztítani a pórusokat és csökkenteni a láthatóságukat a tisztító hatóanyagok és mikro-hámlasztó LHA kombinációja által.',
            pure: false,
            img:'',
        },
        {
            id:15,
            brand: 'La roche Posay',
            name: 'Effaclar gél',
            categoryId: 3,
            description: 'Az EFFACLAR Habzó arctisztító gél gyengéden, szárító hatás nélkül tisztítja a bőrt a kíméletes, jól tolerálható, szigorúan megválogatott tisztító összetevőinek köszönhetően. Eltávolítja a szennyeződéseket és a felesleges faggyút, ezáltal a bőr tiszta és friss lesz.',
            pure: false,
            img:'',
        },
        {
            id:16,
            brand:'La roche posay',
            name: 'Effaclar szérum',
            categoryId: 3,
            description: 'Az EFFACLAR Szérum koncentrált hámlasztó savak és bőrnyugtató niacinamid kombinációját tartalmazza, mely a mitesszereket, a pattanásokat, az akné nyomait és a látható pórusokat célozza. Lemosást nem igénylő formula a finom és tiszta érzésű bőrért.',
            pure: false,
            img:'',
        },
        {
            id:17,
            brand:'La roche posay',
            name: 'Effaclar A.I.',
            categoryId: 3,
            description: 'Az EFFACLAR A.I. egy célzott korrektor krém bőrhibák és pattanások ellen zsíros, pattanásokra hajlamos bőrre. Helyileg, célzottan a bőrhibákra vigyük fel. Az Effaclar A.I. kiváló sminkalap. Nem komedogén',
            pure: false,
            img:'',
        },
        {
            id:18,
            brand: 'La roche posay',
            name: 'Effaclar arcmaszk',
            categoryId: 3,
            description: 'Az EFFACLAR FAGGYÚSZABÁLYOZÓ ARCMASZK kíméletes agyagokkal kifejlesztett formulája eltávolítja a felesleges faggyút és a szemmel nem látható szennyeződéseket (por, szennyezett levegő részecskéi), emellett szabályozza a bőr fénylését. A bőr tisztának látszik, a pórusok kitisztulnak. A bőr tartósan matt és kevésbé zsíros marad.',
            pure: false,
            img:'',
        },
        {
            id:19,
            brand: 'Uriage',
            name: 'Baba bőrgyógyászati olajtusfürdő illatmentes',
            categoryId: 2,
            description: 'Kíméletesen tisztít, táplál, véd, nyugtatja az érzékeny bőrt, enyhíti a viszketést. Uriage termálvízzel ápolja a bőrt. Csecsemők és gyermekek részére / Arcra és testre. ',
            pure: true,
            img:'',
        },
        {
            id:20,
            brand: 'Uriage',
            name:'Baba bőrnyugtató balzsam',
            categoryId: 2,
            description: 'Lipidpótló testápoló balzsam, száraz/rendkívül száraz bőr napi ápolására, és/vagy atópiára hajlamos bőr regenerálására. Mélyen táplál, véd, gátolja az irritációt és a viszketést. Innováció: 48 órás viszketés kiújulás elleni hatás. Uriage termálvízzel ápolja a bőrt. Csecsemők és gyermekek részére / Arcra és testre',
            pure: true,
            img:'',
        },
        {
            id:21,
            brand: 'Uriage',
            name:'Baba olajos tusfürdő babaillattal',
            categoryId: 2,
            description: 'Tisztító, bőrvédő olajtusfürdő arcra, testre, és gyermekek hajas fejbőrére. Lágy gél-olaj textúra.Enyhén illatosított Egy lépésben tisztít és hidratál. Láthatatlan védőréteget hagy a baba bőrén. Védelmet nyújt a kemény víz okozta irritációkkal szemben. ',
            pure: true,
            img:'',
        },
        {
            id:22,
            brand: 'Uriage',
            name: 'Baba krémtusfürdő babaillattal',
            categoryId: 1,
            description: 'Szappanmentes, krémes, habzó textúra. Biológiailag lebomló formula. Egy lépésben tisztít és hidratál. Megvédi a hidrolipid filmréteget. Lággyá, és rugalmassá teszi a bőrt. 2-in-1 tápláló és tisztító fürdető Uriage termálvízzel, csecsemők, gyerekek bőrének extra lágy, napi tisztítására. Arcra, testre. ', 
            pure: true,
            img:'',
        },
        {
            id:23,
            brand: 'Uriage',
            name: 'Babasampon babaillattal',
            categoryId: 1,
            description: ' Extra lágy, magasan tolerált sampon kifejezetten a babák, és gyerekek érzékeny hajának ápolására fejlesztve. Illatosított gél textúra.',
            pure: true,
            img:'',
        },
        {
            id:24,
            brand:'Uriage',
            name: 'Baba testápoló tej',
            categoryId: 1,
            description: 'O/V fluid textúrájú emulzió. Nem ragacsos, gyorsan felszívódik. Arcra, és testre. Száraz, érzékeny bőrre is ajánlott. Csecsemők, gyermekek részére. Könnyű felvitel, Gyors felszívódás jellemzi. A bőrt puhává, és hidratáltá teszi. Megvéd a kiszáradástól. Könnyű, kellemes, illatosított bőrhidratáló emulzió.',
            pure: true,
            img:'',
        },
        {
            id:25,
            brand:'Uriage',
            name: 'Xémose olajtusfürdő',
            categoryId: 2,
            description: 'Lipidpótló olajtusfürdő, száraz/nagyon száraz bőr kíméletes tisztítására különleges lipidfelépítő hatással. Védi a száraz bőrt a víz szárító hatásától. Pótolja a mosakodás során elvesztett zsírokat. Hipoallergén, szappan-, paraben-, illat- és színezékmentes.',
            pure: true,
            img:'',
        },
        {
            id:26,
            brand:'Uriage',
            name:'Xémose nyugtató szemkörnyékápoló',
            categoryId: 2,
            description: 'Száraz/nagyon száraz, irritációra, viszketésre hajlamos szemhéj és szemkörnyék ápolására. Táplál, véd, komfortosabbá teszi a bőrt, azonnal enyhíti az irritációt és a viszketést. Magasan tolerált formulája táplálja és hidratálja a bőrt, erősíti a barriert, korlátozva az allergének behatolását, segíti a meggyengült terület regenerációját, miközben védi azt a külső környezeti agresszióktól, szennyezőktől.',
            pure: true,
            img:'',
        },
        {
            id:27,
            brand:'Uriage',
            name: 'Xémose balzsam',
            categoryId: 2,
            description: 'Száraz/rendkívül száraz bőr napi ápolására és érzékeny, atópiára hajlamos bőr regenerálására. Ajánlott továbbá száraz bőrrel járó betegségek megelőzésére, és szteroidos bőrgyógyászati kezelés kiegészítéseként és utána fenntartó ápolásként.Modern összetétele pótolja a lipideket, táplálja, védi a száraz bőrt, nyugtatja az irritációt és a bőrfelület kivakarását okozó viszketést. Azonnali megnyugvást biztosít és hosszan gátolja az irritáció és a bőrszárazság kiújulását. Késlelteti, csökkenti az irritációkkal, súlyos bőrszárazsággal járó fellángolások kialakulását és visszatérését.',
            pure: true,
            img:'',
        },
        {
            id:28,
            brand: 'Uriage',
            name: 'Xémose cerat krém',
            categoryId: 2,
            description: 'Lipidpótló ápoló krém, száraz/extrém száraz bőr ápolására és atópiára hajlamos bőr regenerálására. Intenzíven táplál, véd, nyugtatja az irritációt és a viszketést.Új generációs emolliens krém, mely táplálja, védi a száraz bőrt, enyhíti az irritációt és a bőrfelület kivakarását okozó viszketést. Azonnali megnyugvást biztosít atópiás tünetek esetén, és hosszan gátolja az irritáció és a bőrszárazság kiújulását.',
            pure: true,
            img: '',
        },
        {
            id: 29,
            brand: 'Uriage',
            name: 'Xémose SOS permet',
            categoryId: 1,
            description: 'A Xémose bőrgyógyászati szakértelme egy könnyű, frissítő permetben, a száraz bőr viszketését azonnal enyhítő, nyugtató hatással. Lipidpótló, tápláló, hidratáló permet, száraz bőr napi ápolására, és/vagy atópiára hajlamos bőr regenerálására. Táplál, véd, gátolja az irritációt és a viszketést. Uriage termálvízzel ápolja a bőrt. Arcra és testre.',
            pure: true,
            img: '',
        },
        {
            id: 30,
            brand: 'Uriage',
            name: 'Bariéderm kenőcs börrepedésekre',
            categoryId: 4,
            description: 'Kirepedezett bőr regenerálására, pl.: a kezek, lábujjak, sarok bőrén megjelenő, nehezen gyógyuló, mély repedések esetén. Rugalmas textúrája elszigeteli és gyorsan javítja a repedéseket. Paraben- és illatanyagmentes, hipoallergén.',
            pure: false,
            img: '',
        },
        {
            id: 31,
            brand: 'Uriage',
            name: 'Bariéderm cica cu-zn+ krém',
            categoryId: 4,
            description: 'Sebkezelő és gyulladáscsökkentő krém, amely csillapítja az irritációt, segíti, gyorsítja a hámsérülések, sebek gyógyulását, regenerálja az atópiára hajlamos bőrt. Ideális az egész család számára, a mindennapokban előforduló bőrsérülések, bőrirritációk kezelésére.',
            pure: true,
            img: '',
        },
        {
            id: 32,
            brand: 'Uriage',
            name: 'Bariéderm bőrgyógyászati masszázsolaj',
            categoryId: 4,
            description: 'Segít megelőzni és korrigálni a striákat. Növeli, javítja a bőr rugalmasságát. Formulája 99,9% természetes összetevőt tartalmaz. Minden bőrtípusra, még a legérzékenyebbre is ajánlott. A BARIÉDERM bőrgyógyászati olajat striák elleni masszírozó kezeléshez fejlesztették ki. Ajánlott a test változásakor, pl. terhességkor, (az első hónaptól és szülés után is), hirtelen súlyváltozáskor (hízás, fogyás), vagy műtét utáni hegekre.',
            pure: false,
            img: '',
        },
        {
            id: 33,
            brand: 'Uriage',
            name: 'Bariéderm kézkrém',
            categoryId: 2,
            description: 'Igazi védő-, barrier krém, mely táplálja, puhítja, ápolja a kezek bőrét. Regenerál, véd, ápol. Uriage termálvízzel tölti fel a bőrt, mely hidratáló, nyugtató, antioxidáns tulajdonságú és erősíti a bőr barriert. Ajánlott: Extrém bőrszárazság esetén, vagy a napi igénybevételtől, vegyi anyagoktól károsodott bőr védelmére, regenerálására.',
            pure: false,
            img: '',
        },
        {
            id: 34,
            brand: 'Uriage',
            name: 'Bariéderm cica daily arcápoló szérum',
            categoryId: 4,
            description: 'Arcápoló szérum károsodott, külső hatásoktól irritálódott, megtört, igénybe vett bőr napi ápolására, és/vagy túlérzékeny bőr ránctalanító, hidratáló ápolására. Megerősíti, helyreállítja a bőr barriert és a mikrobiomot, egységesebb bőrfelszínt és arcszínt nyújt.',
            pure: false,
            img: '',
        },
        {
            id: 35,
            brand: 'Uriage',
            name: 'Hyséac habzó tisztító gél',
            categoryId: 3,
            description: 'Kíméletesen és mélyen kitisztítja az eltömődött pórusokat anélkül, hogy kiszárítaná a bőrt. Csökkenti a pattanások egyik fő okát a fokozott faggyúképződést. Nyugtató, hidratáló hatású, kellemes, friss érzést kölcsönöz a bőrnek. Szőrtüszőgyulladás, irritáció esetén borotvagélként is ajánlott. Szappan-, alkohol-, paraben- és színezékmentes, hipoallergén.',
            pure: false,
            img: '',
        },
        {
            id: 36,
            brand: 'Uriage',
            name: 'Hyséac 3-regul krém',
            categoryId: 3,
            description: 'Átfogó kezelés 3 Uriage szabadalom együttes hatásával a bőrhibák és azok visszatérése ellen. Kitisztítja az eltömődött pórusokat, gátolja a P.acnes gyulladást okozó hatását, antibakteriális hatású, csökkenti a fokozott faggyúképződést. Az első termék, mely a Mikrobiofilm szabályozásával egyensúlyba hozza a bőrflórát, csökkenti a pattanásokat okozó P.acnes tapadását és túlszaporodását.',
            pure: false,
            img: '',
        },
        {
            id: 37,
            brand: 'Uriage',
            name: 'Hyséac mat krém',
            categoryId: 3,
            description: 'Zsíros vagy kombinált, fénylő bőr mindennapi ápolására. Több szinten is megváltoztatja a bőr nem kívánt fénylő, zsíros állapotát: semlegesíti a bőr csillogását a fényt szétszóró mikrorészecskéknek köszönhetően, abszorbeálja a felesleges faggyút és összehúzza a zsíros bőrre jellemző tág pórusokat.',
            pure: false,
            img: '',
        },
        {
            id: 38,
            brand: 'Uriage',
            name: 'Hyséac szérum',
            categoryId: 3,
            description: 'Exkluzív Uriage szabadalmak, AHA komplex és Uriage termálvíz együttes hatásával segít gyorsan csökkenteni a mitesszerek, pattanások és zsírosan fénylő bőr tüneteit, és gátolja azok visszatérését.',
            pure: false,
            img: '',
        },
        {
            id: 39,
            brand: 'Uriage',
            name: 'Hyséac sos paté',
            categoryId: 3,
            description: 'Pattánások SOS, célzott kezelésére. Extra gyors hatás, akár egy éjszaka alatt. Keratolitikus, antibakteriális, faggyúképződést csökkentő, nyugtató és szárító hatású.',
            pure: false,
            img: '',
        },
        {
            id: 40,
            brand: 'Uriage',
            name: 'Hyséac arcmaszk',
            categoryId: 3,
            description: 'Lehúzható maszk mélytisztító, pórusösszehúzó, mattító és bőrhibák elleni hatással. A lehúzható maszk használatával a pórusok mérete láthatóan csökken, a bőr textúrája azonnal finomabbá, az arcszín frissebbé válik. Rendszeres használata a bőrt tisztábbá, láthatóan szebbé teszi, és segít gátolni a mitesszerek és pattanások kialakulását.Tulajdonságai: Kaolin agyag és Cink tartalmával mélyen kitisztítja a pórusokat, eltávolítja a láthatatlan szennyeződéseket, felszívja a felesleges faggyút, mattító hatásával csökkenti a zsíros bőr csillogását és enyhíti a bőrhibákat.',
            pure: false,
            img: '',
        },
        {
            id: 41,
            brand: 'La roche posay',
            name: 'Cicaplast B5+ balzsam',
            categoryId: 4,
            description: 'Egy többcélú balzsam, amely segít nyugtatni és védeni az irritált bőrt. Az egész család számára használható és 14 indikáción tesztelték. A különleges Tribioma prebiotikum erejével. Madecassosiddal (egy regeneráló hatóanyaggal), bőrnyugtató panthenollal és antibakteriális hatóanyaggal gazdagítva. Nyugtatja, táplálja és védi a száraz bőrt, a bőr barrierfunkciójának regenerálásáért.',
            pure: true,
            img: '',
        },
        {
            id: 42,
            brand: 'La roche posay',
            name: 'Cicaplast B5 spray',
            categoryId: 4,
            description: 'Érintésmentes felvitel az optimális higiéniáért.Összetevőinek köszönhetően a CICAPLAST Spray B5 regenerál és nyugtat: Bőrbarrier regenerálás: [Madecassoside] + [Réz - Mangán] Száraz, irritált területek nyugtatása: [5% Panthenol] Kíméletes a bőr mikrobiomjával: [Nem szárító formula] + [mannóz] + [fiziológiás ph]',
            pure: true,
            img: '',
        },
        {
            id: 43,
            brand: 'La roche posay',
            name: 'Cicaplast B5 habzó tisztító gél',
            categoryId: 4,
            description: 'Ultragyengéd habzó arc- és testlemosó kiszárítás nélküli tisztításhoz és bőrnyugtatáshoz. Bőrnyugtató hatású panthenollal, kíméletes antibakteriális hatóanyagokkal és hidratáló glicerinnel. Tisztít, nyugtat és feltölti a bőrfelszínt.',
            pure: true,
            img: '',
        },
        {
            id: 44,
            brand: 'La roche posay',
            name: 'Cicaplast kézkrém',
            categoryId: 2,
            description: 'Regeneráló, bőrnyugtató kézkrém, amely óvja és támogatja a kéz bőrének védőfunkcióját [4% niacinamid] és [30% glicerin] tartalmának köszönhetően, valamint rendkívül kellemes érzetet nyújt.',
            pure: false,
            img: '',
        },
        {
            id: 45,
            brand: 'La roche posay',
            name: 'Cicaplast ajakápoló',
            categoryId: 4,
            description: 'Ez a regeneráló barrier-balzsam nyugtatja a bőrt és segít helyreállítani az epidermiszt a kicserepesedett, berepedezett és irritált ajkakon és egyéb területeken. ',
            pure: false,
            img: '',
        },
        {
            id: 46,
            brand: 'La roche posay',
            name: 'Lipikar surgras szappan',
            categoryId: 2,
            description: 'Lipidekben gazdag, hidratáló, szappan összetevőt nem tartalmazó formulája kíméletesen tisztítja és táplálja a száraz bőrt a természetes védőréteg fenntartásáért.',
            pure: true,
            img: '',
        },
        {
            id: 47,
            brand: 'La roche posay',
            name: 'Lipikar balzsam light AP+M',
            categoryId: 2,
            description: 'AZ ÚJ, KÖNNYŰ TEXTÚRÁJÚ LIPIKAR AP+M BALZSAM segít nyugtatni a diszkomfort-érzetet, csökkenteni a száraz bőr miatti viszketést, és meghosszabbítani a száraz bőr nyugalmi állapotát. Táplálja a bőrt és segít regenerálni a bőrbarrier-funkciót. Formuláját úgy fejlesztették, hogy gyermekek és felnőttek atópiás ekcémára hajlamos bőrére is megfelelő legyen. Új, gyorsan beszívódó textúra, még meleg, párás időjárás esetén is.',
            pure: true,
            img: '',
        },
        {
            id: 48,
            brand: 'Uriage',
            name: 'Xémose ajakápoló',
            categoryId: 1,
            description: 'Illatmentes ajakápoló stift száraz ajkakra, mely hosszan tartóan hidratál, táplál, véd és regenerál. She vaj tartalma intenzíven táplálja a száraz ajkakat. C- és E-vitamin tartalma anti-oxidáns és szabadgyökfogó képességével véd a külső agresszióktól. Hialuronsav tartalma hosszan tartóan hidratálja a száraz ajkakat.',
            pure: false,
            img: '',
        },
        {
            id: 49,
            brand: 'Uriage',
            name: 'Xémose arcápló krém',
            categoryId: 2,
            description: 'Új generációs arckrém, száraz/nagyon száraz bőrre, különleges lipidfelépítő hatással. Krémes textúra, gyorsan felszívódik, nem ragad. Hipoallergén, szappan-, paraben-, illat- és színezékmentes.',
            pure: true,
            img: '',
        },
        {
            id: 50,
            brand: 'Uriage',
            name: 'Baba cold krém',
            categoryId: 1,
            description: 'Ultra tápláló összetétel, puhává varázsolja a bőrt. Véd a mindennapos időjárási agresszióktól (hideg, szél, víz). Magasan tolerált, v/o emulzió. Száraz, nagyon száraz, érzékeny bőrre is ajánlott. Csecsemők, gyerekek, felnőttek részére. Arcra, testre. Méhviaszon alapuló összetétele táplálja a száraz bőrt, helyreállítja hidrolipid védőrétegét, puhaságát, komfortérzetét. Uriage termálvíz tartalma hidratálja, nyugtatja az érzékeny bőrt és komfortos érzést biztosít.',
            pure: true,
            img: '',
        },

    ]
}

// {
//     id: ,
//     brand: '',
//     name: '',
//     categoryId: ,
//     description: '',
//     pure: ,
//     img: '',
// },